# Generated by Django 3.2.3 on 2021-06-15 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_post_post_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_body', models.TextField()),
                ('post_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.autor')),
            ],
        ),
    ]
